### ISSUE TITLE
EndpointResolverWithOptionsFunc helper does not implement EndpointResolverWithOptions.ResolveEndpoint

### ISSUE THREAD

**Issue by tiedotguy** [aws/aws-sdk-go-v2#1498]
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

The `EndpointResolverWithOptionsFunc` convenience wrapper does not properly implement the `EndpointResolverWithOptions` interface.  Specifically the interface requires `options ...interface{}`, and the wrapper only takes `options interface{}`.

Appears to be introduced in #1274

### Expected behavior

Build succeeds

### Current behavior

```
./main.go:6:6: cannot use aws.EndpointResolverWithOptionsFunc(nil) (type aws.EndpointResolverWithOptionsFunc) as type aws.EndpointResolverWithOptions in assignment:
        aws.EndpointResolverWithOptionsFunc does not implement aws.EndpointResolverWithOptions (wrong type for ResolveEndpoint method)
                have ResolveEndpoint(string, string, interface {}) (aws.Endpoint, error)
                want ResolveEndpoint(string, string, ...interface {}) (aws.Endpoint, error)
```

### Steps to Reproduce

```
package main

import "github.com/aws/aws-sdk-go-v2/aws"

func main() {
	var _ aws.EndpointResolverWithOptions = aws.EndpointResolverWithOptionsFunc(nil)
}
```

### Possible Solution

Add `...` in the right places in endpoints.go.  Build succeeds when they are put in place on the 3 lines.

https://github.com/aws/aws-sdk-go-v2/blob/fafd921e6870b6fedcae3bf9c966c460b828d9ef/aws/endpoints.go#L186-L190

### AWS Go SDK version used

1.11.0

### Compiler and Version used

1.17.1

### Operating System and version

Linux, Windows

**Comment by skmcgrail** [comment]
Thank you for taking the time to report this bug @tiedotguy. This was not intentional and we will get a fix put together for our upcoming release later this week.
