### ISSUE TITLE
S3 `ReplicationRuleFilter` and `LifecycleRuleFilter` change causes compilation errors

### ISSUE THREAD

**Issue by ewbankkit** [aws/aws-sdk-go-v2#2833]
### Acknowledgements

- [X] I have searched (https://github.com/aws/aws-sdk/issues?q=is%3Aissue) for past instances of this issue
- [X] I have verified all of my SDK modules are up-to-date (you can perform a bulk update with `go get -u github.com/aws/aws-sdk-go-v2/...`)

### Describe the bug

The change to S3 `ReplicationRuleFilter` and `LifecycleRuleFilter` introduced in https://github.com/aws/aws-sdk-go-v2/pull/2831 causes compilation errors:

```
Error: internal/service/s3/bucket_lifecycle_configuration.go:716:95: undefined: types.LifecycleRuleFilterMemberAnd
Error: internal/service/s3/bucket_lifecycle_configuration.go:747:74: undefined: types.LifecycleRuleFilterMemberTag
```

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

CHANGELOG entry notes a breaking change.

### Current Behavior

Compilation error.

### Reproduction Steps

```go
import (
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
)

	result := &types.LifecycleRuleFilterMemberAnd{
		Value: types.LifecycleRuleAndOperator{},
	}
```

### AWS Go SDK V2 Module Versions Used

```console
% grep 'service/s3' go.mod 
	github.com/aws/aws-sdk-go-v2/service/s3 v1.65.3
	github.com/aws/aws-sdk-go-v2/service/s3control v1.49.2
	github.com/aws/aws-sdk-go-v2/service/s3outposts v1.28.2
```

### Compiler and Version used

go 1.23.2

### Operating System and version

macos

**Comment by lucix-aws** [comment]
I've updated the release notes to explicitly note the break: https://github.com/aws/aws-sdk-go-v2/commit/f46593cf8fbabc48da6f6c2517a818715211d099
